"""E10 — ESG-presentable report packs (HTML + CSV, no raw JSON required)."""

from __future__ import annotations

import csv
import io
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.core.config import Settings, get_settings
from app.db.models import CarbonReport


@dataclass
class EsgPack:
    report_id: int
    plant_code: str
    html: str
    csv_text: str
    filename_stem: str


def _pack_dir(settings: Settings) -> Path:
    path = Path(settings.carbon_esg_pack_dir)
    if not path.is_absolute():
        path = Path(__file__).resolve().parents[2] / path
    path.mkdir(parents=True, exist_ok=True)
    return path


def build_esg_pack(
    report: CarbonReport,
    plant_code: str,
    *,
    settings: Settings | None = None,
) -> EsgPack:
    cfg = settings or get_settings()
    scope3 = float(getattr(report, "scope3_kgco2", None) or 0.0)
    scope3_detail: dict[str, Any] = {}
    raw_detail = getattr(report, "scope3_detail_json", None)
    if raw_detail:
        try:
            scope3_detail = json.loads(raw_detail)
        except json.JSONDecodeError:
            scope3_detail = {}

    total = float(report.scope1_kgco2) + float(report.scope2_kgco2) + scope3
    assurance = getattr(report, "assurance_status", None) or "draft"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    stem = f"esg_pack_{plant_code}_{report.period_type}_{report.id}"

    rows = [
        ("Plant", plant_code),
        ("Period type", report.period_type),
        ("Period start", report.period_start.isoformat() if report.period_start else ""),
        ("Period end", report.period_end.isoformat() if report.period_end else ""),
        ("Assurance status", assurance),
        ("Scope 1 (kg CO₂)", f"{report.scope1_kgco2:.2f}"),
        ("Scope 2 (kg CO₂)", f"{report.scope2_kgco2:.2f}"),
        ("Scope 3 light (kg CO₂)", f"{scope3:.2f}"),
        ("Total Scopes 1–3 (kg CO₂)", f"{total:.2f}"),
        ("Carbon intensity (kg CO₂/t)", f"{(report.carbon_intensity_kgco2_ton or 0):.2f}"),
        ("Product (t)", f"{(report.product_ton or 0):.2f}"),
        ("Samples", str(report.sample_count or 0)),
        ("Factors version", report.factors_version or ""),
        ("Scope 3 factors", scope3_detail.get("factors_version", "")),
        ("Submitted by", getattr(report, "submitted_by", None) or ""),
        ("Approved by", getattr(report, "approved_by", None) or ""),
        ("Locked by", getattr(report, "locked_by", None) or ""),
        ("Pack generated", generated),
        ("Registry", cfg.carbon_market_registry_name),
    ]

    # CSV
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Khalij iEMS ESG Sustainability Pack"])
    writer.writerow(["Field", "Value"])
    for k, v in rows:
        writer.writerow([k, v])
    writer.writerow([])
    writer.writerow(["Scope 3 category", "kg CO₂"])
    writer.writerow(["Cat3 fuel upstream", scope3_detail.get("cat3_fuel_upstream_kgco2", "")])
    writer.writerow(["Cat1 purchased goods", scope3_detail.get("cat1_purchased_goods_kgco2", "")])
    writer.writerow(["Cat5 waste", scope3_detail.get("cat5_waste_kgco2", "")])
    csv_text = buf.getvalue()

    # HTML (printable)
    def esc(s: Any) -> str:
        return (
            str(s)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )

    table_rows = "".join(
        f"<tr><th>{esc(k)}</th><td>{esc(v)}</td></tr>" for k, v in rows
    )
    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/>
<title>ESG Pack — {esc(plant_code)} #{report.id}</title>
<style>
  body {{ font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; margin: 2rem; background: #f7f5f0; }}
  h1 {{ font-size: 1.6rem; margin-bottom: 0.2rem; }}
  .sub {{ color: #555; margin-bottom: 1.5rem; }}
  table {{ border-collapse: collapse; width: 100%; max-width: 720px; background: #fff; }}
  th, td {{ border: 1px solid #ccc; padding: 0.55rem 0.75rem; text-align: left; }}
  th {{ width: 45%; background: #eef2ea; }}
  .badge {{ display: inline-block; padding: 0.15rem 0.5rem; border: 1px solid #2d5a27; color: #2d5a27; font-size: 0.85rem; }}
  footer {{ margin-top: 1.5rem; font-size: 0.85rem; color: #666; }}
  @media print {{ body {{ background: #fff; margin: 0.5rem; }} }}
</style></head><body>
<h1>Khalij iEMS — ESG Sustainability Pack</h1>
<p class="sub">Enterprise carbon inventory for audit / ESG review · <span class="badge">{esc(assurance)}</span></p>
<table>{table_rows}</table>
<footer>Generated by Khalij iEMS · Not raw API JSON · Factors are plant-configured IPCC-style + light Scope 3 proxies.</footer>
</body></html>
"""

    out_dir = _pack_dir(cfg)
    (out_dir / f"{stem}.html").write_text(html, encoding="utf-8")
    (out_dir / f"{stem}.csv").write_text(csv_text, encoding="utf-8")

    return EsgPack(
        report_id=report.id,
        plant_code=plant_code,
        html=html,
        csv_text=csv_text,
        filename_stem=stem,
    )
